package wg

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"

	"golang.org/x/crypto/curve25519"
)

// GenerateClientConfig uses pure-Go X25519 key generation and builds a wg-quick config file.
// Output: wg-client-<peerName>.conf in CWD
func GenerateClientConfig(peerName, address string) error {
	// generate 32 random bytes for private key
	var priv [32]byte
	if _, err := rand.Read(priv[:]); err != nil {
		return fmt.Errorf("read rand: %w", err)
	}

	// clamp per RFC7748 for X25519
	priv[0] &= 248
	priv[31] &= 127
	priv[31] |= 64

	// compute public key
	var pub [32]byte
	curve25519.ScalarBaseMult(&pub, &priv)

	privEncoded := base64.StdEncoding.EncodeToString(priv[:])
	pubEncoded := base64.StdEncoding.EncodeToString(pub[:])

	conf := fmt.Sprintf(`[Interface]
PrivateKey = %s
Address = %s
DNS = 1.1.1.1

[Peer]
# Replace PublicKey and Endpoint with your server values
PublicKey = <SERVER_PUBLIC_KEY>
Endpoint = <SERVER_HOST:51820>
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25

# keys generated by orchestrator:
# client public: %s
`, privEncoded, address, pubEncoded)

	fn := fmt.Sprintf("wg-client-%s.conf", peerName)
	if err := os.WriteFile(fn, []byte(conf), 0600); err != nil {
		return err
	}
	return nil
}
